version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - '33306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - '38080:8080'
